name: build
on:
  workflow_dispatch:

jobs:
  apk:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Force Checkout Latest
        uses: actions/checkout@v4
        with:
          # This ensures we don't build the old cached "Demo" code
          ref: main
          fetch-depth: 1

      - name: 2. Setup Environment
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: 3. Clean and Repair Project
        run: |
          # Kill old folders to prevent conflict
          rm -rf android
          
          # Recreate the structure using your package identity
          flutter create . --org com.royal --project-name my_cloud_compiler --platforms android --overwrite
          
          # Restore dependencies
          flutter pub get

      - name: 4. Compile APK
        run: flutter build apk --release

      - name: 5. Store APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: "build/app/outputs/flutter-apk/*.apk"
